IAV.Merchant.WebMvc/Controllers/ProductListingLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using IAV.Merchant.WebMvc.CustomAuthentication;
using IAV.Merchant.WebMvc.Models;
using IAV.Merchant.WebMvc.Services;

namespace IAV.Merchant.WebMvc.Controllers
{
    [CustomAuthorize(Roles = "merchant")]
    public class ProductListingLogsController : Controller
    {
        ProductListingLogsService service = new ProductListingLogsService();

        // GET: Orders
        public ActionResult Index()
        {
            ProductListingLogsSearchViewModel model = new ProductListingLogsSearchViewModel();
            model.PageNo = 1;
            model.NoOfResultPerPage = 1;

            return View(SearchProductListingLogs(model));
        }


        //// GET: Order Details
        //public ActionResult Details(int id)
        //{
        //    var ProductLog = service.GetProductLogById(id);
        //    return View(productLog);
        //}

        private ProductListingLogsSearchViewModel SearchProductListingLogs(ProductListingLogsSearchViewModel model)
        {
            CustomPrincipal principal = (CustomPrincipal)System.Web.HttpContext.Current.User;

            string merchantId = principal.UserId.ToString();
            return service.Search(model, merchantId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ProductListingLogsSearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            return View(SearchProductListingLogs(model));
        }

        //[HttpPost]
        //public JsonResult save(OrderMaster order)
        //{
        //    //bool status = false;
        //    //DateTime dateOrg;
        //    //var isValidDate = DateTime.TryParseExact(order.OrderDateString, "mm-dd-yyyy", null, System.Globalization.DateTimeStyles.None, out dateOrg);
        //    //if (isValidDate)
        //    //{
        //    //    order.OrderDate = dateOrg;
        //    //}

        //    //var isValidModel = TryUpdateModel(order);
        //    //if (isValidModel)
        //    //{
        //    //    using (MyDatabaseEntities dc = new MyDatabaseEntities())
        //    //    {
        //    //        dc.OrderMasters.Add(order);
        //    //        dc.SaveChanges();
        //    //        status = true;
        //    //    }
        //    //}
        //    //return new JsonResult { Data = new { status = status } };
        //}
    }
}

IAV.Merchant.WebMvc/Views/ProductListingLogs/index.cshtml
@using IAV.Merchant.WebMvc.Models
@model ProductListingLogsSearchViewModel
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Prodcut Listing Logs</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
@using (Html.BeginForm("Index", "ProductListingLogs", FormMethod.Post, new { id = "productListingLogsForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>                            
                            <th>
                                merchant_id
                            </th>
                            <th>
                                Product Log Desc
                            </th>
                            <th>
                                Created Date
                            </th>
                            <th>
                                Last Update
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.ProductLogs)
                        {
                            var createdDate = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(@item.created_at));
                            var updatedDate = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(@item.last_update));
                            <tr>
                                <th>
                                    @Html.ActionLink(@item.id.ToString(), // <-- Link text
                                    "Details",
                                    new { id = item.id },
                                    null)
                            </th>
                            <td>@item.merchant_id</td>
                            <td>@item.description</td>
                            <td>@createdDate</td>
                            <td>@updatedDate</td>
                        </tr>
                        }
                    </tbody>
                </table>
                <input type="hidden" id="hdPageNo" name="PageNo" />
                <input type="hidden" id="hdNoOfResultPerPage" name="NoOfResultPerPage" value="@Model.NoOfResultPerPage" />
                <ul class="pagination">
                    @foreach (var item in Model.Pages)
                    {
                        <li class="@(item.is_enable ? "" : "active")"><a href="javascript:PagerClick(@item.id);">@item.name</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>

}

@section scripts{
    <script type="text/javascript">
        function PagerClick(index) {
            document.getElementById("hdPageNo").value = index;
            document.getElementById("productListingLogsForm").submit();
        }
    </script>
}