IAV.AdminMainPortal/ViewModels/MerchantProductViewModel.cs
using IAV.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IAVAdmin.ViewModels
{
    public class MerchantProductViewModel
    {
        private markeet_demoEntities db = new markeet_demoEntities();
        public List<SelectListItem> ddlProducts { get; set; }
        public List<product> Products { get; set; }
        public List<merchant> Merchants { get; set; }
        public product_merchant MP { get; set; }
        public List<MPDetail> MerchantProducts { get; set; } 
        public MPDetail SelectedProduct { get; set; }

        public MerchantProductViewModel()
        {
          
            try
            {
                Products = db.products.ToList();
                Merchants = db.merchants.ToList();
                MP = db.product_merchant.Where(m => m.merchant_id == "3").FirstOrDefault();
                MerchantProducts = GetMerchantProducts("3");
                SelectedProduct = GetSelectedProduct(MP.id);
            }
            catch (Exception e) 
            {
                Console.WriteLine(e.Message);
            }
            
        }

        public MPDetail GetSelectedProduct(string id)
        {
            //return db.products.Where(p => p.id.ToString() == MP.product_id).FirstOrDefault();
            return MerchantProducts.Where(mp => mp.id == id).FirstOrDefault();
        }

        private List<MPDetail> GetMerchantProducts(string mid)
        {
            /*
            var prodcts = from p in db.products
                          let pid = from pm in db.product_merchant
                                    where pm.merchant_id == mid
                                    select pm.product_id
                          where pid.Contains(p.id.ToString())
                          select p;
            */
            List <MPDetail > details = new List<MPDetail>();
            foreach (var item in db.product_merchant.ToList())
            {
                if(item.merchant_id == mid)
                {
                    MPDetail mpd = new MPDetail();
                    mpd.id = item.id;
                    mpd.quantity_available = item.quantity_available;
                    mpd.discounted_price = item.discounted_price;
                    mpd.actual_price = item.actual_price;
                    mpd.merchantId = item.merchant_id;
                    foreach (var p in db.products.ToList())
                    {
                        if (p.id.ToString() == item.product_id)
                        {
                            mpd.productId = p.id.ToString();
                            mpd.Name = p.name;
                            break;
                        }
                    }
                    details.Add(mpd);
                }

            }
            return details;
        }
    }

    public class MPDetail
    {
        public string id { get; set; }
        public string productId { get; set; }
        public string merchantId { get; set; }
        public string Name { get; set; }
        public long? quantity_available { get; set; }
        public decimal? actual_price { get; set; }
        public decimal? discounted_price { get; set; }

    }
}

IAV.AdminMainPortal/Controllers/MerchantProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using System.Web.Mvc.Html;
using IAVAdmin.ViewModels;
using IAV.Data.Models;
using System.Data.Entity;


namespace IAVAdmin.Controllers
{
    public class MerchantProductsController : Controller
    {
        private markeet_demoEntities db = new markeet_demoEntities();
        MerchantProductViewModel vmMerchantProducts = new MerchantProductViewModel();
        
        // GET: MerchantProducts
        public ActionResult Index()
        {
            return View(vmMerchantProducts);
        }

        // GET: MerchantProducts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //product_merchant product_merchant = db.product_merchant.Find(id);
            //product product = db.products.Find(Convert.ToInt64(id));
            vmMerchantProducts.SelectedProduct = vmMerchantProducts.GetSelectedProduct(id);
            if (vmMerchantProducts.SelectedProduct == null)
            {
                return HttpNotFound();
            }
            return View(vmMerchantProducts);
        }

        // GET: MerchantProducts/Create
        public ActionResult Create()
        {
            vmMerchantProducts.ddlProducts = new List<SelectListItem>();
            foreach (var prod in vmMerchantProducts.Products)
            {
                vmMerchantProducts.ddlProducts.Add(new SelectListItem() { Text = prod.name, Value = prod.id.ToString() });
            }
            return View(vmMerchantProducts);
        }

        // POST: MerchantProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MerchantProductViewModel vm)
        {
            //change merchant id
            vm.MP.merchant_id = "3";
            vm.MP.product_id = Request.Form["ddlProduct"].ToString();
            vm.MP.id = (Convert.ToInt32(db.product_merchant.ToList().Max(mp => mp.id)) + 1).ToString();

            if (ModelState.IsValid)
            {
                db.product_merchant.Add(vm.MP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        // GET: MerchantProducts/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //change merchant id
            //product_merchant product_merchant = db.product_merchant.Where(mp => mp.merchant_id == "3" && mp.product_id == id.ToString()).FirstOrDefault();
            vmMerchantProducts.MP = db.product_merchant.Where(mp => mp.merchant_id == "3" && mp.id == id.ToString()).FirstOrDefault();

            vmMerchantProducts.ddlProducts = new List<SelectListItem>();
            foreach (var prod in vmMerchantProducts.Products)
            {
                if (prod.id.ToString() == vmMerchantProducts.MP.product_id)
                    vmMerchantProducts.ddlProducts.Add(new SelectListItem() { Text = prod.name, Value = prod.id.ToString(), Selected = true });
                else
                    vmMerchantProducts.ddlProducts.Add(new SelectListItem() { Text = prod.name, Value = prod.id.ToString() });
            }

            if (vmMerchantProducts.MP == null)
            {
                return HttpNotFound();
            }
            return View(vmMerchantProducts);
        }

        // POST: MerchantProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MerchantProductViewModel vm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vm.MP).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vm);
        }

        // GET: MerchantProducts/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //product_merchant product_merchant = db.product_merchant.Find(id);

            //ToDo: change merchant it
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vmMerchantProducts.SelectedProduct = vmMerchantProducts.GetSelectedProduct(id);
            if (vmMerchantProducts.SelectedProduct == null)
            {
                return HttpNotFound();
            }
            return View(vmMerchantProducts);
        }

        // POST: MerchantProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            //product_merchant product_merchant = db.product_merchant.Find(id);
            //ToDo: change merchant it
            product_merchant product_merchant = db.product_merchant.Where(mp => mp.merchant_id == "3" && mp.id == id.ToString()).FirstOrDefault();
            db.product_merchant.Remove(product_merchant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

IAV.AdminMainPortal/Controllers/MmerchantsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using System.IO;
using System.Collections.Generic;
using IAV.Data.Models;


namespace IAVAdmin
{
    public class MmerchantsController : Controller
    {
        private markeet_demoEntities db = new markeet_demoEntities();
        
        // GET: Mmerchants
        public ActionResult Index()
        {
            List<merchant> abc = new List<merchant>();
            //IEnumerable<getNearestMerchants_Result> NearestMerchants = db.getNearestMerchants(133, "1.098", "9.099");
            try {
                abc = db.merchants.ToList(); 
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
           
            return View(abc);
        }

        public JsonResult GetMerchants()
        {
            //IEnumerable<getNearestMerchants_Result> NearestMerchants = db.getNearestMerchants(133, "1.098", "9.099");
            var result = db.merchants.ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // GET: Mmerchants/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchant merchant = db.merchants.Find(id);
            if (merchant == null)
            {
                return HttpNotFound();
            }
            return View(merchant);
        }

        // GET: Mmerchants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mmerchants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mid,business_name,gstin,tan,cin,signature,address_line1,address_line2,pincode,city,state,phone_no,store_no, latitude, longitude,delivery_charges,charge")] merchant merchant, HttpPostedFileBase gstin, HttpPostedFileBase tan, HttpPostedFileBase cin, HttpPostedFileBase storePic)
        {
            CheckFileIsNull(gstin, "gstin");
            CheckFileIsNull(tan, "tan");
            CheckFileIsNull(cin, "cin");
            CheckFileIsNull(storePic, "storePic");
            if (ModelState.IsValid)
            {
                merchant.gstin = SaveFile(gstin);
                merchant.tan = SaveFile(tan);
                merchant.cin = SaveFile(cin);
                merchant.store_picture = SaveFile(storePic);
                merchant.mid = ((Convert.ToInt32(db.merchants.Max(m => m.mid))) + 1).ToString();
                merchant.latitude = Convert.ToDecimal(TempData["lat"]);
                merchant.longitude = Convert.ToDecimal(TempData["long"]);
                db.merchants.Add(merchant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(merchant);
        }

        [HttpPost]
        
        public ActionResult UpdateLoc(string lat, string lon)
        {
            TempData["lat"] = lat;
            TempData["long"] = lon;
            return new EmptyResult();
        }

        // GET: Mmerchants/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchant merchant = db.merchants.Find(id);
            if (merchant == null)
            {
                return HttpNotFound();
            }
            return View(merchant);
        }

        // POST: Mmerchants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(merchant merchant)
        {
           if (ModelState.IsValid)
            {
                db.Entry(merchant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(merchant);
        }

        
        public void CheckFileIsNull(HttpPostedFileBase file, string name)
        {
            if (file == null || file.ContentLength == 0)
            {
                ModelState.AddModelError(name, "This field is required");
            }
        }

        public string SaveFile(HttpPostedFileBase file)
        {
            var uploadDir = "~/Uploads";
            var localPath = Path.Combine(Server.MapPath(uploadDir), file.FileName);
            var localUrl = Path.Combine(uploadDir, file.FileName);
            file.SaveAs(localPath);
            return localUrl;
        }

        // GET: Mmerchants/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchant merchant = db.merchants.Find(id);
            if (merchant == null)
            {
                return HttpNotFound();
            }
            return View(merchant);
        }

        // POST: Mmerchants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            merchant merchant = db.merchants.Find(id);
            db.merchants.Remove(merchant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IAV.AdminMainPortal/Views/MerchantProducts/Create.cshtml
@model IAVAdmin.ViewModels.MerchantProductViewModel

@{
    ViewBag.Title = "Add Product";
}

<h2>Add Product</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.Label("Select Product", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ddlProduct",
                    (List<SelectListItem>)Model.ddlProducts,
                    "Select Product",
                    new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.quantity_available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.quantity_available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.quantity_available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.actual_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.actual_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.actual_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.discounted_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.discounted_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.discounted_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IAV.AdminMainPortal/Views/MerchantProducts/Delete.cshtml
@model IAVAdmin.ViewModels.MerchantProductViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.SelectedProduct.Name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.quantity_available)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.quantity_available)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.actual_price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.actual_price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.discounted_price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.discounted_price)
        </dd>
    </dl>
</div>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IAV.AdminMainPortal/Views/MerchantProducts/Details.cshtml
@model IAVAdmin.ViewModels.MerchantProductViewModel
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.SelectedProduct.Name )</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.quantity_available)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.quantity_available)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.actual_price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.actual_price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelectedProduct.discounted_price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelectedProduct.discounted_price)
        </dd>
    </dl>
</div>
<p>
   @Html.ActionLink("Back to List", "Index")
</p>

IAV.AdminMainPortal/Views/MerchantProducts/Edit.cshtml
@model IAVAdmin.ViewModels.MerchantProductViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MP.id)

        <div class="form-group">
            @Html.Label("Select Product", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ddlProduct",
                    (List<SelectListItem>)Model.ddlProducts,
                    "Select Product",
                    new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.quantity_available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.quantity_available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.quantity_available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.actual_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.actual_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.actual_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MP.discounted_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MP.discounted_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MP.discounted_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IAV.AdminMainPortal/Views/MerchantProducts/Index.cshtml
@model IAVAdmin.ViewModels.MerchantProductViewModel
@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>
@*<p>
    @Html.ActionLink("View Merchants", "Index", "Mmerchants")
</p>*@
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Quantity Available
        </th>
        <th>
            Actual Price
        </th>
        <th>
            Discounted Price
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.MerchantProducts) {
    <tr>
        <td>
            @item.Name
        </td>
        <td>
            @item.quantity_available
        </td>
        <td>
            @item.actual_price
        </td>
        <td>
            @item.discounted_price
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>