IAV.Merchant.WebMvc/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using IAV.Merchant.WebMvc.CustomAuthentication;
using IAV.Merchant.WebMvc.Models;
using IAV.Merchant.WebMvc.Services;

namespace IAV.Merchant.WebMvc.Controllers
{
    [CustomAuthorize(Roles = "merchant")]
    public class OrdersController : Controller
    {
        OrderService service = new OrderService();

        // GET: Orders
        public ActionResult Index()
        {
            OrderSearchViewModel model = new OrderSearchViewModel();
            model.PageNo = 1;
            model.NoOfResultPerPage = 1;

            return View(SearchOrders(model));
        }


        // GET: Order Details
        public ActionResult Details(int id)
        {
            var order = service.GetOrderById(id);
            return View(order);
        }

        private OrderSearchViewModel SearchOrders(OrderSearchViewModel model)
        {
            CustomPrincipal principal = (CustomPrincipal)System.Web.HttpContext.Current.User;

            string merchantId = principal.UserId.ToString();
            return service.Search(model, merchantId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(OrderSearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            return View(SearchOrders(model));
        }

        //[HttpPost]
        //public JsonResult save(OrderMaster order)
        //{
        //    //bool status = false;
        //    //DateTime dateOrg;
        //    //var isValidDate = DateTime.TryParseExact(order.OrderDateString, "mm-dd-yyyy", null, System.Globalization.DateTimeStyles.None, out dateOrg);
        //    //if (isValidDate)
        //    //{
        //    //    order.OrderDate = dateOrg;
        //    //}

        //    //var isValidModel = TryUpdateModel(order);
        //    //if (isValidModel)
        //    //{
        //    //    using (MyDatabaseEntities dc = new MyDatabaseEntities())
        //    //    {
        //    //        dc.OrderMasters.Add(order);
        //    //        dc.SaveChanges();
        //    //        status = true;
        //    //    }
        //    //}
        //    //return new JsonResult { Data = new { status = status } };
        //}
    }
}

IAV.Merchant.WebMvc/Views/Orders/Details.cshtml
@model IAV.Data.Models.product_order_detail
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Order</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.order_id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.order_id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.merchant_id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.merchant_id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.price_item)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.price_item)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.created_at)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.created_at)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.last_update)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.last_update)
            </dd>

        </dl>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.product_order.id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.buyer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.buyer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.code)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.code)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.comment)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.comment)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product_order.phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_order.phone)
            </dd>            
        </dl>
    </div>
</div>

IAV.Merchant.WebMvc/Views/Orders/Index.cshtml
@using IAV.Merchant.WebMvc.Models
@model OrderSearchViewModel
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Orders</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
@using (Html.BeginForm("Index", "Orders", FormMethod.Post, new { id="orderForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Order Id
                            </th>
                            <th>
                                Product Name
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                Created Date
                            </th>
                            <th>
                                Last Update
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.Orders)
                        {
                            var createdDate = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(@item.created_at));
                            var updatedDate = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(@item.last_update));
                        <tr>
                            <th>@Html.ActionLink(@item.id.ToString(), // <-- Link text
                                    "Details",
                                    new { id = item.id },
                                    null)
                            </th>
                            <td>@item.order_id</td>
                            <td>@item.product_name</td>
                            <td>@item.amount</td>
                            <td>@item.price_item</td>
                            <td>@createdDate</td>
                            <td>@updatedDate</td>
                        </tr>
                        }
                    </tbody>
                </table>
                <input type="hidden" id="hdPageNo" name="PageNo" />
                <input type="hidden" id="hdNoOfResultPerPage" name="NoOfResultPerPage" value="@Model.NoOfResultPerPage" />
                <ul class="pagination">
                    @foreach (var item in Model.Pages)
                    {
                        <li class="@(item.is_enable ? "" : "active")"><a href="javascript:PagerClick(@item.id);">@item.name</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>

}

@section scripts{
    <script type="text/javascript">
        function PagerClick(index) {
            document.getElementById("hdPageNo").value = index;
            document.getElementById("orderForm").submit();
        }
    </script>
}